"""Initial migration

Revision ID: bfc89101c0e9
Revises: 
Create Date: 2024-10-25 00:37:14.513139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc89101c0e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_v_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postgres_server', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postgres_port', sa.Integer(), nullable=False),
    sa.Column('postgres_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postgres_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postgres_db', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
